using System;
using System.Reflection;
using System.Runtime.CompilerServices;

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("SexyCalculator")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("Midnight Computers")]
[assembly: AssemblyProductAttribute("")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2014, Midnight Computers")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("0.0.0.134")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyKeyNameAttribute("")]

